macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1
  script: |
    brew install rust asciidoctor
    brew tap slp/krun
    brew install libkrun buildah
    sudo chown -R $(whoami) /usr/local/bin
    make clean
    make install
    krunvm --help
  artifacts:
    paths: ["target/release/krunvm"]